### ISSUE TITLE
Inspect why error no more includes a human-readable message 

### ISSUE THREAD

**Issue by malikankit** [ChorusOne/solido#177] opened 2021-06-15 14:18 UTC
Cross-referencing comment (3 occurences) in `tests/test_multisig.py`

```
    # TODO: Previously the error included a human-readable message, why does it
    # only include the error code now? Something to do with different Anchor
    # versions?
 ```

**Comment by ruuda** [comment] 2021-08-06 12:03
I think it’s a problem with Anchor after all, maybe a bug introduced in a later version.

```rust
    let program_error = ProgramError::from(multisig::ErrorCode::AlreadyExecuted);
    println!("{:?}", program_error);
    let anchor_error = multisig::Error::from(program_error);
    println!("{:?}", anchor_error);
```
prints
```
Custom(105)
ProgramError(Custom(105))
```
while I would have expected it to print
```
Custom(105)
ErrorCode(AlreadyExecuted)
```
it seems that converting back the error code to the structured error is broken.

**Comment by ruuda** [comment] 2021-08-12 15:06
I believe I found the cause of this: https://github.com/project-serum/anchor/pull/354#issuecomment-897717786

**Comment by ruuda** [comment] 2021-08-13 09:57
#360 adds a workaround for this problem, so let’s close the issue.

**Closed by ruuda** 2021-08-13 09:57 UTC
Labels: tag-todos
